### ISSUE TITLE
Dynamically change lang

### ISSUE THREAD

**Issue by jonathandion** [koalazak/i18n-express#10]
Hi,

I would like to update the lang if you user browse ```/fr``` or ```/en``` . I added a middleware to dynamically update the defaultLang value but it's doesn't work.

```javascript
var config = {
	i18n: {
		translationsPath: path.join(__dirname, 'locales'),
		siteLangs: ["en","fr"],
		textsVarName: 't',
		defaultLang: 'fr',
	}
}

var url_has_lang_regex = /^\/([a-z]{2})(\/|$)/;
app.use(function(req, res, next) {
	var lang_matches = req.url.match( url_has_lang_regex );
	if((config.i18n.siteLangs).indexOf(lang_matches[1]) >= 0) {
		console.log(lang_matches[1])
	   	config.i18n.defaultLang = lang_matches[1];
	}
	console.log(config)
	next();
});
app.use(i18n(config.i18n));
```

Thanks.

**Comment by koalazak** [comment]
the `defaultLang` is not the actual language. Its just the initial value if there is no language seted. You can not change `defaultLang` at middleware time, or I mean, you can but its not taked into account, its only just for a default value at startup time.

If you want to change the lang you should use `clang` queryparam or set `req.session[cookieLangName]` to your desired lang on your middleware.

regards,
