### ISSUE TITLE
defaultLang not working

### ISSUE THREAD

**Issue by agungwiseso** [koalazak/i18n-express#11]
Hi, Thanks for the i18n-express package, I wanna ask something, I have a code like this :

```
app.use(i18n({
    translationsPath: path.join(__dirname, 'i18n'),
    siteLangs: ["id","en"],
    textsVarName: 'text',
    defaultLang: 'id',
    paramLangName : 'lang'
}));
```

Why defaultLang not working? When i open my web, defaultLang always to en.
Thanks

**Comment by koalazak** [comment]
Hi, what language you are using in your brwoser? if you dont set `browserEnable` to false, then thus library will try to use you browser language. The default lang is only if others methods fails.
Take a look at `Options` readme

**Comment by agungwiseso** [comment]
Hi @koalazak, my browser using english. I try to set `browserEnable : false` and it works. Thanks for your help and for the great package.
