### ISSUE TITLE
Translations are not working on my template file.

### ISSUE THREAD

**Issue by eece** [koalazak/i18n-express#17]
Hi, I can't show my translations on my app. My template engine is Pug.

**in app.js:**

var cookieParser = require('cookie-parser');
var i18n=require("i18n-express"); // <-- require the module
var session = require('express-session')

app.use(i18n({
  translationsPath: __dirname + '/i18n', //
  siteLangs: ["en","tr"],
  textsVarName: 'translations',
  defaultLang: "tr"
}));
app.use(session({
  secret: 'secret',
  saveUninitialized: true,
  resave: true
}));
module.exports = app;

**tr.js:**

{
"WELCOME_MSG": "Hi! Welcome!",
"CONTACT_TEXT": "More bla"
}

**index.pug:**
h1 #{translations.WELCOME_MSG}

**Comment by koalazak** [comment]
`tr.js` file should be called `tr.json`
