### ISSUE TITLE
Cannot see a way to use it on method

### ISSUE THREAD

**Issue by mikzuit** [koalazak/i18n-express#19]
Cool work man, but ... Is me or there ir no way to use language variables on method like i18n documentacion point like this:
```
app.get('/de', function(req, res){
  var greeting = res.__('Hello');
});
```
Cannot find a way to use in model or controllers, I end it up using both (i18n and i18n-express).

Please let me know if is just me that cannot find it.

**Comment by koalazak** [comment]
You are right, It is on the TODO:
https://github.com/koalazak/i18n-express/blob/master/TODO

PRs are welcome :p

**Comment by mikzuit** [comment]
ok, no problem , thanks
